### PR TITLE
Export/Import Extensions list

### PR DESCRIPTION
**Pull request by benmccallum**
Added basic support for:
- exporting your currently installed extensions to a file.
- importing a file of same format to install them (if not already).

Initial idea was a bulk installer (https://twitter.com/benmccallum/status/574719626329767937) but I like the idea of export/import when moving between machines. Or just as a way to share between devs.

We could easily achieve a bulk installer by having the SearchDialog support dynamically adding ComboBoxes  as you find and add your wanted extension to a queue. Then on click just have it run through them like I do on the import.

### CODE REVIEW

**Comment by benmccallum** [comment]
Hey @madskristensen, This is just me playing around with the idea of speeding up setup time for a bunch of extensions across machines. Was dumping some ideas in a Twitter thread [here](https://twitter.com/benmccallum/status/574719626329767937). I like the idea of just having an import file I can share around my team, but maybe also even offering from the extension fly out menu some presets like "O you do web dev? Install these!".

**Comment by benmccallum** [comment]
cc: @sayedihashimi

**Comment by madskristensen** [comment]
Good idea. I like it

**Comment by benmccallum** [comment]
Do you think it belongs with your extension or should I spin it off into a different one?

**Comment by madskristensen** [comment]
No, I think it makes sense in this extension

**Comment by benmccallum** [comment]
Alright, I'll tidy it up, make it a bit more friendly and let you know when it's ready for review.

I'm new to WPF/XAML so I'll need to figure out how to create a nicer filename picker for the export and file picker for the import since there's nothing native.

**Comment by benmccallum** [comment]
Sorry Mads, I haven't had much time of late but I'll try and get this finished off this weekend.

**Comment by madskristensen** [comment]
Let me know if you're still up for this or it should be closed?

**Comment by benmccallum** [comment]
Still keen. Will have a crack this weekend.

**Comment by benmccallum** [comment]
Hi @madskristensen, Tidied it up. Pretty basic but doesn't need to be complicated. In fact, would it be better to just have these as menu options instead of in a dialog? Let me know how you'd like to proceed!

**Comment by madskristensen** [comment]
Can you share screenshots?

**Comment by SeriousM** [comment]
@benmccallum Thank you for contributing your idea and implementation. I searched for a way to export a list of all extensions because I have to switch machines frequently.
Could you two @benmccallum and @madskristensen push this PR a bit please? It's such a great idea, I would love to see it implemented!
Thank you both so much! :+1:

**Comment by madskristensen** [comment]
@SeriousM Why not use the Roaming Extension Manager https://visualstudiogallery.msdn.microsoft.com/7b421a95-c32c-4433-a2be-a41b276013ab ?

**Comment by SeriousM** [comment]
> @SeriousM Why not use the Roaming Extension Manager

Because I didn't know it exists! Thank you for pointing it out :)
My only concern is that I have to use the same login for every VS instance but have to work with different ones depending on the client.

Thank you anyway :+1:

**Comment by benmccallum** [comment]
Will finish this PR this weekend, promise. Got very close but a billion things on at the moment! Don't know how guys like Mads manage full time work and open source :P Total respect!

**Comment by benmccallum** [comment]
Hey @madskristensen, this PR is ready. Only 10 months later ;)  

There is now a new flyout menu under yours called "Export/Import Extensions" which has two submenu commands "Export" and "Import".

- Export: launches a save file dialog for the user to choose where to save their exported extensions list.
- Import: launches a file picker dialog for the user to choose an existing exported extension list file.

All messages are written to a new "Extension Updater" Output window pane and the messaging is pretty elaborate so the user knows what went on.

Have a look and hopefully you can get this up in the VS gallery to help some people like @SeriousM and myself swapping machines.

Cheers!

**Comment by madskristensen** [comment]
Awesome. Thanks you!

**Comment by SeriousM** [comment]
@benmccallum thank you!!!
@mad when do you plan to release the new version on the gallery?

**Comment by madskristensen** [comment]
When it's been tested. You can get the CI build here http://vsixgallery.com/extension/cb8900a0-79fb-4c76-a6d6-f4e88d3384d2/ and help test

**Comment by SeriousM** [comment]
Ok, the first problem is that I can't install it on the 2015 community edition.
I don't know how to extend [.vsixmanifest](https://github.com/madskristensen/ExtensionUpdater/blob/master/src/source.extension.vsixmanifest) the extension to support it and also the syntax for the dependencies are wired (`[xxx)`??)

Could you please lend me your hand?

**Comment by madskristensen** [comment]
This extension is only supported on VS2013 because VS2015 already has support for auto-updating extensions out of the box.

**Comment by SeriousM** [comment]
> This extension is only supported on VS2013 because VS2015 already has support for auto-updating extensions out of the box.

Hmm, I guess you mean the Roaming Extension Manager, right?
The problem is, that the Roaming Extension Manager is using the logged in user, but I have a few - for every customer one - and therefore it doesn't work out for me.

**Comment by madskristensen** [comment]
No, VS2015 will auto-update extensions by default. Roaming Extension Manager let's you move extensions between different installations of VS2015

**Comment by SeriousM** [comment]
err, sorry. I should start reading the whole post before answering it.
yes, the update is build in, but now you have an export feature as well and that's something vs2015 doesn't support yet (as I need it).
Thats a problem now, right?

**Comment by madskristensen** [comment]
Right. This feature should perhaps have been in it's own extension

**Comment by benmccallum** [comment]
Should I pull it own into its own repo? I did always struggle with it living in an extension called Auto Updater.

**Comment by madskristensen** [comment]
I think that would make sense

**Comment by benmccallum** [comment]
No worries. Will have a look tonight and let you both know! 

Revert this PR merge.

**Comment by SeriousM** [comment]
> Will have a look tonight and let you both know!

wow, cool! thank you!

**Comment by benmccallum** [comment]
Hey guys, 

I've gone ahead and abstracted my feature out into its own repo: https://github.com/benmccallum/BulkExtensionManager

Right now I'm running AppVeyor CI builds and producing VSIX packages with Mads' awesome powershell scripts to: 
https://ci.appveyor.com/project/benmccallum/bulkextensionmanager/build/artifacts

I downloaded it, did a manual install and although the installation seemed to go okay, restarting VS I got a "Failed to load package" message. In the VS ActivityLog.xml reported it couldn't load Microsoft.VisualStudio.ExtensionManager

`
  <entry>
    <record>685</record>
    <time>2016/02/07 05:56:42.778</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [BulkExtensionManagerPackage]</description>
    <guid>{CB8900A0-79FB-4C76-A6D6-F4E88D3384D3}</guid>
  </entry>
  <entry>
    <record>686</record>
    <time>2016/02/07 05:56:42.800</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [BulkExtensionManagerPackage]</description>
    <guid>{CB8900A0-79FB-4C76-A6D6-F4E88D3384D3}</guid>
    <hr>80070002</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.ExtensionManager, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>
  <entry>
    <record>687</record>
    <time>2016/02/07 05:56:42.800</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [BulkExtensionManagerPackage]</description>
    <guid>{CB8900A0-79FB-4C76-A6D6-F4E88D3384D3}</guid>
    <hr>80070002</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.ExtensionManager, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>
`

Any tips @madskristensen? Seems strange that the xml log is saying v14.0.0.0 rather than 12.

**Comment by benmccallum** [comment]
Interestingly, if I just build the .sln locally and take that VSIX (Debug or Release) and install it, no problems at all.

It's just the artifact from appveyor that is having problems. The message at the start, and the extension's menu options are in the UI but don't work.

Is there anything special about your AppVeyor project setup @madskristensen? I literally just added new from from GitHub repo.

At the moment am running with Vsix-PublishToGallery commented out (https://github.com/benmccallum/BulkExtensionManager/blob/master/appveyor.yml) as I'm not sure how that works yet. Are the parameters in your PS script coming from variables in AppVeyor? Where is the security in that POST to the VS Gallery?

Thanks!

**Comment by madskristensen** [comment]
What VS version you targeting? Make sure all the references match that version

**Comment by benmccallum** [comment]
I'm targeting the same version as this repo was. It's basically the same project file too so references should be the same. Will have a play when I get a chance. Thanks!

**Pull request merged**
